  {
    _T("DEFAULT"),
    _T("IDR_WAV_DRIP"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Pan mode ON"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Pan mode OFF"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("AutoZoom ON"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("AutoZoom OFF"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Calibrate ON"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Calibrate OFF"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Closest Airfield Changed!"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("SnailTrail OFF"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("SnailTrail ON Long"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("SnailTrail ON Short"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Vario Sounds ON"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Vario Sounds OFF"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Dropped marker"),
    _T("IDR_WAV_BEEPBWEEP"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Waiting for GPS connection"),
    NULL,
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Restarting comm. ports"),
    NULL,
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Waiting for GPS fix"),
    NULL,
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("XCI Error"),
    _T("IDR_FAIL"),
    true,
    std::chrono::milliseconds(30000),
  },
  {
    _T("MacCready Value"),
    NULL,
    true,
    std::chrono::milliseconds(5000),
  },
  {
    _T("Auto MacCready ON"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Auto MacCready OFF"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Task aborted"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Task Resume"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Bugs performance"),
    NULL,
    true,
    std::chrono::milliseconds(5000),
  },
  {
    _T("Ballast %"),
    NULL,
    true,
    std::chrono::milliseconds(5000),
  },
  {
    _T("Logger ok"),
    _T("IDR_INSERT"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Logger off"),
    _T("IDR_REMOVE"),
    true,
    std::chrono::milliseconds(1500),
  },
  {
    _T("Status"),
    NULL,
    true,
    std::chrono::milliseconds(60000),
  },
  {
    _T("Battery low"),
    _T("IDR_FAIL"),
    true,
    std::chrono::milliseconds(5000),
  },
  {
    _T("Screen Mode Full"),
    NULL,
    true,
    std::chrono::milliseconds(1000),
  },
