set(Form_SOURCES
        Form/Button.cpp
        Form/ButtonPanel.cpp
        Form/CharacterButton.cpp
        Form/CheckBox.cpp
        Form/Control.cpp
        Form/DataField/Angle.cpp
        Form/DataField/Base.cpp
        Form/DataField/Boolean.cpp
        Form/DataField/ComboList.cpp
        Form/DataField/Enum.cpp
        Form/DataField/File.cpp
        Form/DataField/Float.cpp
        Form/DataField/GeoPoint.cpp
        Form/DataField/Integer.cpp
        Form/DataField/Number.cpp
        Form/DataField/Password.cpp
        Form/DataField/Prefix.cpp
        Form/DataField/RoughTime.cpp
        Form/DataField/String.cpp
        Form/DataField/Time.cpp
        Form/DigitEntry.cpp
        Form/Draw.cpp
        Form/Edit.cpp
        Form/Form.cpp
        Form/Frame.cpp
        Form/GridView.cpp
        Form/HLine.cpp
        Form/List.cpp
        Form/Panel.cpp
        Form/ScrollBar.cpp
        Form/TabDisplay.cpp
        Form/TabMenuDisplay.cpp
)

